### ISSUE TITLE
Negative Timeout value

### ISSUE THREAD

**Issue by njewsbury** [njewsbury/gravitational-simulation#6]
While running the default simulation set with properties : 
1. Scale Size : 0.03
2. FPS : 900
3. Timeout Val : 0.0

An exception occured that froze the simulation:

llabF3:~/Downloads> java -jar space-time-render-1.0-SNAPSHOT-jar-with-dependencies.jar
[ INFO] ConfigPanel                  :: Initializing Config Panel. 
[ INFO] RenderFrame               :: Run New Simulation. 
[ INFO] RenderFrame               :: Starting new simulation! 
[ INFO] SimulationEngine          :: Inserting orbital object 'earth' 
[ INFO] SimulationEngine          :: Inserting orbital object 'comet' 
[ INFO] RenderFrame               :: Simulation thread initialized. 
[ INFO] RenderFrame               :: New Simulation. 
Exception in thread "Thread-1" java.lang.IllegalArgumentException: timeout value is negative
	at java.lang.Thread.sleep(Native Method)
	at ca.jewsbury.gravity.render.engine.SimulationEngine.run(SimulationEngine.java:163)
	at java.lang.Thread.run(Thread.java:744)

I think it may only be due to the high FPS number given, (which isn't a true FPS... but)  However, this should be a simple fix within the thread logic.

**Comment by njewsbury** [comment]
Did a check for negative sleep values before calling Thread.sleep, if a negative value is found it only sleeps for 1ms.  No issues have shown up since.
